version: "3.9"

name: beam_pipelines

services:
  beam:
    container_name: beam
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      IMAGES_BUCKET_NAME: ${IMAGES_BUCKET_NAME}
      TFRECORD_BUCKET: ${TFRECORD_BUCKET}
      LABELS_BUCKET: ${LABELS_BUCKET}
    volumes:
      - ./pipelines:/beam_pipelines/pipelines
      - ${PWD}/beam_pipelines/service_account.json:/beam_pipelines/service_account.json
    depends_on:
      - spark

  spark:
    image: bitnami/spark:3
    environment:
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
