version: "3.9"

name: labelapp

services:
  url-app:
    container_name: url-app
    build:
      context: ./url_app
      dockerfile: Dockerfile

  postgres:
    container_name: postgres
    image: postgres:latest
    privileged: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
