version: "3.9"

name: image_scraper

services:
  scrapy-base:
    container_name: scrapy-base
    build:
      context: .
      dockerfile: base.Dockerfile

  scrapyd:
    container_name: scrapyd
    build:
      context: .
      dockerfile: scrapyd.Dockerfile
    ports:
      - "6800:6800"
    env_file:
      - .env
    volumes:
      - ${PWD}/image_scraper/service_account.json:/src/service_account.json
    depends_on:
      - scrapy-base
