version: "3.9"

name: image_scraper

services:
  scrapyd:
    container_name: scrapyd
    build:
      context: .
      dockerfile: scrapyd.Dockerfile
    ports:
      - "6800:6800"
    environment:
      CATS_BUCKET_NAME: ${CATS_BUCKET_NAME}
      PROJECT_ID: ${PROJECT_ID}
    networks:
      - airflow_default

  scrapyd_deploy:
    container_name: scrapyd_deploy
    build:
      context: .
      dockerfile: scrapyd_deploy.Dockerfile
    depends_on:
      - scrapyd
    networks:
      - airflow_default

  # Kafka Server
  zookeeper-service:
    container_name: zookeeper-service
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - airflow_default

  kafka-service:
    container_name: kafka-service
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-service:2181
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-service:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    networks:
      - airflow_default
    depends_on:
      - zookeeper-service

networks:
  airflow_default:
    external: true
