version: "3.9"

name: image_scraper

services:
  scrapy-base:
    container_name: scrapy-base
    build:
      context: .
      dockerfile: base.Dockerfile

  scrapyd:
    container_name: scrapyd
    build:
      context: .
      dockerfile: scrapyd.Dockerfile
    ports:
      - "6800:6800"
    environment:
      IMAGES_BUCKET_NAME: ${IMAGES_BUCKET_NAME}
      PROJECT_ID: ${PROJECT_ID}
      KAFKA_LISTENER: ${KAFKA_LISTENER}
      DEPLOY_ENV: "docker"
    volumes:
      - ${PWD}/image_scraper/service_account.json:/src/service_account.json
    depends_on:
      - scrapy-base

  # Kafka Server
  zookeeper-service:
    container_name: zookeeper-service
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"

  kafka-service:
    container_name: kafka-service
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-service:2181
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-service:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-service
