name: CI for Beam Pipelines
on:
  push:
    paths:
      - 'beam_pipelines/**'
      - '.github/workflows/beam-ci.yml'
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build beam pipelines container to run tests
        run: docker build beam_pipelines --file beam_pipelines/to_tfrecord.Dockerfile --tag pipelines

      - name: Run tests in Docker container
        run: |
          docker run pipelines python -m unittest discover tests
