name: CI for Image Scraping
on:
  push:
    paths:
      - 'image_scraper/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build scrapyd-deploy to run tests
        run: docker build image_scraper --file image_scraper/scrapyd_deploy.Dockerfile --tag scrapyd-deploy

  test-scrapy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests in Docker container
        run: |
          docker run scrapyd-deploy python -m unittest discover tests
